# Generated by Django 5.1.4 on 2025-08-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildEducationVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=100)),
                ('volunteer_phone', models.CharField(max_length=20)),
                ('volunteer_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('qualification', models.CharField(choices=[('high-school', 'High School (12th)'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Post Graduate'), ('bed', 'B.Ed'), ('med', 'M.Ed'), ('other', 'Other')], max_length=20)),
                ('experience', models.CharField(blank=True, choices=[('none', 'No formal experience'), ('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=10)),
                ('age_group', models.CharField(choices=[('pre-primary', 'Pre-Primary (3-5 years)'), ('primary', 'Primary (6-10 years)'), ('both', 'Both Pre-Primary & Primary')], max_length=20)),
                ('teaching_mode', models.CharField(choices=[('online', 'Online Only'), ('offline', 'In-Person Only'), ('both', 'Both Online & In-Person')], max_length=10)),
                ('subjects', models.TextField()),
                ('availability', models.CharField(choices=[('weekdays-morning', 'Weekdays Morning (9 AM - 12 PM)'), ('weekdays-afternoon', 'Weekdays Afternoon (2 PM - 5 PM)'), ('weekdays-evening', 'Weekdays Evening (6 PM - 8 PM)'), ('weekends', 'Weekends'), ('flexible', 'Flexible Schedule')], max_length=30)),
                ('motivation', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
