# Generated by Django 5.1.4 on 2025-08-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('skill_interest', models.CharField(max_length=100)),
                ('preferred_schedule', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('has_basic_tools', models.BooleanField(default=False)),
                ('motivation', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='childeducationvolunteer',
            name='volunteer_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
