# Generated by Django 5.1.4 on 2025-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shram', '0002_trainingrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=100)),
                ('skill_needed', models.CharField(max_length=100)),
                ('preferred_mode', models.CharField(choices=[('online', 'Online Sessions'), ('offline', 'In-Person Training'), ('hybrid', 'Both Online & Offline')], max_length=20)),
                ('availability', models.CharField(choices=[('weekdays-morning', 'Weekdays Morning'), ('weekdays-evening', 'Weekdays Evening'), ('weekends', 'Weekends'), ('flexible', 'Flexible Schedule')], max_length=30)),
                ('urgency', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20, null=True)),
                ('learning_goal', models.TextField()),
                ('background', models.TextField(blank=True, null=True)),
                ('specific_requirements', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
