# Generated by Django 5.1.4 on 2025-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shram', '0003_volunteerrequest_alter_trainingrequest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTEEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.IntegerField()),
                ('previous_schooling', models.TextField(blank=True, null=True)),
                ('parent_name', models.CharField(max_length=100)),
                ('guardian_relation', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Legal Guardian'), ('relative', 'Relative'), ('ngo', 'NGO Representative'), ('other', 'Other')], max_length=20)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('preferred_schools', models.TextField(blank=True, null=True)),
                ('documents', models.TextField(blank=True, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
