# Generated by Django 5.1.4 on 2025-08-15 18:30

import django.db.models.deletion
import shram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shram', '0005_incidentreport_incidentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingDonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=10)),
                ('clothing_details', models.TextField(help_text='Types and quantities of clothing')),
                ('condition', models.CharField(choices=[('new', 'New'), ('gently-used', 'Gently Used'), ('needs-repair', 'Needs Repair')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shram.models.clothing_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shram.clothingdonationrequest')),
            ],
        ),
    ]
